//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public EMPLOYEE()
        {
            this.BOOK_ISSUENCE = new HashSet<BOOK_ISSUENCE>();
        }
    
        public int employeeId { get; set; }
        public string employeeName { get; set; }
        public string Designation { get; set; }
        public string employeeContact { get; set; }
    
        public virtual ICollection<BOOK_ISSUENCE> BOOK_ISSUENCE { get; set; }
    }
}
