//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINE
    {
        public int fineId { get; set; }
        public int fineAmount { get; set; }
        public int memberId { get; set; }
        public System.DateTime paidOn { get; set; }
    
        public virtual MEMBER MEMBER { get; set; }
    }
}
