//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        public MEMBER()
        {
            this.BOOK_ISSUENCE = new HashSet<BOOK_ISSUENCE>();
            this.FINEs = new HashSet<FINE>();
        }
    
        public int memberId { get; set; }
        public string memberName { get; set; }
        public string memberContact { get; set; }
    
        public virtual ICollection<BOOK_ISSUENCE> BOOK_ISSUENCE { get; set; }
        public virtual ICollection<FINE> FINEs { get; set; }
    }
}
